# Generated by Django 3.0 on 2024-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241208_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayments',
            name='due_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taxpayments',
            name='payment_date',
            field=models.CharField(max_length=100),
        ),
    ]
